#sudo lsof -i:2181


version: '3'

services:
  zookeper:    
    image: wurstmeister/zookeeper
    container_name: zookeper
    ports:
      - "2181:2181"
    

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"    
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      
